export const PATH = {
    ROOT: '/',
    SIGN_IN: '/signin',
    SIGN_UP: '/signup',
    DASHBOARD: '/dashboard',
    PROFILE: 'profile',
    COMPANY: 'company',
    DOCUMENTS: 'document',
    CONTRACT: '/contract',
    COMMANDER: '/commander',
    MEETING_ROOM: '/meetingroom',
    VIDEO_ROOM: '/videoroom/:meetingId',
    PROFILE: 'profile',
    COMPANY: 'company',
    DOCUMENTS: 'documents',
} as const